/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as DrillLevelIdStepIdRouteImport } from './routes/drill.$levelId.$stepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillLevelIdStepIdRoute = DrillLevelIdStepIdRouteImport.update({
  id: '/drill/$levelId/$stepId',
  path: '/drill/$levelId/$stepId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/drill/$levelId/$stepId': typeof DrillLevelIdStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/drill/$levelId/$stepId': typeof DrillLevelIdStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/drill/$levelId/$stepId': typeof DrillLevelIdStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/learn' | '/onboarding' | '/review' | '/drill/$levelId/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/onboarding' | '/review' | '/drill/$levelId/$stepId'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/onboarding'
    | '/review'
    | '/drill/$levelId/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRoute
  OnboardingRoute: typeof OnboardingRoute
  ReviewRoute: typeof ReviewRoute
  DrillLevelIdStepIdRoute: typeof DrillLevelIdStepIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/$levelId/$stepId': {
      id: '/drill/$levelId/$stepId'
      path: '/drill/$levelId/$stepId'
      fullPath: '/drill/$levelId/$stepId'
      preLoaderRoute: typeof DrillLevelIdStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRoute,
  OnboardingRoute: OnboardingRoute,
  ReviewRoute: ReviewRoute,
  DrillLevelIdStepIdRoute: DrillLevelIdStepIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
